// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kljzjwbtnjtsovtkbwac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsanpqd2J0bmp0c292dGtid2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTk1MTEsImV4cCI6MjA2ODQzNTUxMX0.kt8WDa_N7w9dwNtFQHFze6hZPJbK4Y0Wg1Z7V8n1ZF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});